import { UserExercise } from "./types";

export const exercises: UserExercise[] = [
  {
    id: 1,
    exercise: {
      id: 1,
      key: "yuris-shoulder-band-warmup",
      name: "Yuri's Shoulder Band Warmup",
      category: "WARM_UP",
      type: "WARM_UP",
      targetSets: 1,
      targetRepsMin: 5,
      targetRepsMax: 10,
      targetRest: 0,
      additionalRest: 0,
      mediaLink: "https://www.youtube.com/watch?v=6y_AU-aGhVE",
      comments: "<ul><li>Can also be done with a tee-shirt</li></ul>",
      duration: false,
    },
  },
  {
    id: 2,
    exercise: {
      id: 2,
      key: "squat-sky-reaches",
      name: "Squat Sky Reaches",
      category: "WARM_UP",
      type: "WARM_UP",
      targetSets: 1,
      targetRepsMin: 5,
      targetRepsMax: 10,
      targetRest: 0,
      additionalRest: 0,
      mediaLink: "https://www.youtube.com/watch?v=lbozu0DPcYI&t=42s",
      comments: null,
      duration: false,
    },
  },
  {
    id: 3,
    exercise: {
      id: 3,
      key: "gmb-wrist-prep",
      name: "GMB Wrist Prep",
      category: "WARM_UP",
      type: "WARM_UP",
      targetSets: 1,
      targetRepsMin: 10,
      targetRepsMax: null,
      targetRest: 0,
      additionalRest: 0,
      mediaLink: "https://www.youtube.com/watch?v=mSZWSQSSEjE",
      comments: "<ul><li>Do as many reps as you want</li></ul>",
      duration: false,
    },
  },
  {
    id: 4,
    exercise: {
      id: 4,
      key: "deadbugs-both-legs",
      name: "Deadbugs (Both Legs)",
      category: "WARM_UP",
      type: "WARM_UP",
      targetSets: 1,
      targetRepsMin: 30,
      targetRepsMax: 30,
      targetRest: 0,
      additionalRest: 0,
      mediaLink: "https://www.youtube.com/watch?v=HFv2WwgeVMk",
      comments: null,
      duration: true,
    },
  },
  {
    id: 5,
    exercise: {
      id: 5,
      key: "arch-hangs-warmup",
      name: "Arch Hangs (Warmup)",
      category: "WARM_UP",
      type: "WARM_UP",
      targetSets: 1,
      targetRepsMin: 10,
      targetRepsMax: 10,
      targetRest: 0,
      additionalRest: 0,
      mediaLink: "https://www.youtube.com/watch?v=C995b3KLXS4&t=7s",
      comments:
        '<ul><li>Add these after you reach Negative Pullups</li><li>Beginner attempts will look more like <a href="https://www.youtube.com/watch?v=HoE-C85ZlCE">this</a></li></ul>',
      duration: false,
    },
  },
  {
    id: 6,
    exercise: {
      id: 6,
      key: "support-hold-warmup",
      name: "Parallel Bar Support Hold (Warmup)",
      category: "WARM_UP",
      type: "WARM_UP",
      targetSets: 1,
      targetRepsMin: 30,
      targetRepsMax: 30,
      targetRest: 0,
      additionalRest: 0,
      mediaLink:
        "https://antranik.org/wp-content/uploads/2014/01/antranik-holding-support-hold-on-parallel-bars.jpg",
      comments:
        "<ul><li>Arms straight</li><li>Body straight or slightly hollow</li><li>Depress the shoulderblades (<a href='https://www.reddit.com/r/bodyweightfitness/wiki/kb/positioning'>what does that even mean?</a>)</li><li>The stability of the PB allows you to build some strength and perfect your form. Have a minimum 60sec hold before moving on to the rings</li></ul>",
      duration: true,
    },
  },
  {
    id: 7,
    exercise: {
      id: 7,
      key: "squat-warmup",
      name: "Squat (Warmup)",
      category: "WARM_UP",
      type: "WARM_UP",
      targetSets: 1,
      targetRepsMin: 10,
      targetRepsMax: 10,
      targetRest: 0,
      additionalRest: 0,
      mediaLink: "https://www.youtube.com/watch?v=zJBLDJMJiDE",
      comments:
        "<ul><li>Stand up straight at the top</li><li>Go as low as you can, preferably until the hips are below the knees</li><li>Dig your big toe and heel into the ground</li><li>Keep your knee in-line with your toes</li><li>Don't let the knees come inward on either the descend or the ascend; think about pushing the knees out</li></ul>",
      duration: false,
    },
  },
  {
    id: 8,
    exercise: {
      id: 8,
      key: "pull-up-negatives",
      name: "Pull-up Negatives",
      category: "FIRST_PAIR",
      type: "PULL_UP",
      targetSets: 3,
      targetRepsMin: 5,
      targetRepsMax: 8,
      targetRest: 90,
      additionalRest: 90,
      mediaLink: "https://www.youtube.com/watch?v=EkpJkHpJXmM",
      comments:
        "<ul><li>Jump to the top of the pull-up position, then <b>slowly</b> (as slowly as you can), lower yourself until your arms are straight</li><li>Build up to <b>10sec negatives!</b></li></ul>",
      duration: false,
    },
  },
  {
    id: 9,
    exercise: {
      id: 9,
      key: "bulgarian-split-squats",
      name: "Bulgarian Split Squat",
      category: "FIRST_PAIR",
      type: "SQUAT",
      targetSets: 3,
      targetRepsMin: 5,
      targetRepsMax: 8,
      targetRest: 90,
      additionalRest: 90,
      mediaLink: "https://www.youtube.com/watch?v=kkdmHTASZg8&t=75s",
      comments:
        "<ul><li>Pretend the barbell doesn't exist.</li><li>You can progress this further by elevating both your legs</li></ul>",
      duration: false,
    },
  },
  {
    id: 10,
    exercise: {
      id: 10,
      key: "negative-dips",
      name: "Negative Dips",
      category: "SECOND_PAIR",
      type: "DIP",
      targetSets: 3,
      targetRepsMin: 5,
      targetRepsMax: 8,
      targetRest: 90,
      additionalRest: 90,
      mediaLink: "https://www.youtube.com/watch?v=T3Scqw1BbCc",
      comments:
        "<ul><li>This exercise is only the descent. To get to the starting position you can jump or use a box or anything</li><li>Lower yourself with control. Work up to 10 sec descents</li></ul>",
      duration: false,
    },
  },
  {
    id: 11,
    exercise: {
      id: 11,
      key: "hamstring-slide",
      name: "Hamstring Slide",
      category: "SECOND_PAIR",
      type: "HINGE",
      targetSets: 3,
      targetRepsMin: 5,
      targetRepsMax: 8,
      targetRest: 90,
      additionalRest: 90,
      mediaLink: "https://www.youtube.com/watch?v=Dlazt593cuA",
      comments:
        "<ul><li>This exercise can bridge the gap between SLDL and Nordic Curls</li><li>You will need a towel, socks, sliders, carpet etc. material which allows you to perform this movement smoothly</li><li>Keep PPT/Neutral Pelvis. Hands supporting at sides for support as needed</li><li>Ascend by squeezing glutes, pulling your ankles to your glutes, contracting your hamstrings</li><li>Descend by sliding ankles out under control</li><li>As before, but pull ankles back to glutes after eccentric movement, contracting the hamstrings and glutes</li></ul>",
      duration: false,
    },
  },
  {
    id: 12,
    exercise: {
      id: 12,
      key: "incline-rows",
      name: "Incline Rows",
      category: "THIRD_PAIR",
      type: "ROW",
      targetSets: 3,
      targetRepsMin: 5,
      targetRepsMax: 8,
      targetRest: 90,
      additionalRest: 90,
      mediaLink: "https://www.youtube.com/watch?v=LR2EnFWpVao",
      comments:
        "<ul><li>Perform a row, but with the body position somewhere between vertical and horizontal. Go closer to horizontal to make it harder.</li></ul>",
      duration: false,
    },
  },
  {
    id: 13,
    exercise: {
      id: 13,
      key: "diamond-pushup",
      name: "Diamond Pushup",
      category: "THIRD_PAIR",
      type: "PUSH_UP",
      targetSets: 3,
      targetRepsMin: 5,
      targetRepsMax: 8,
      targetRest: 90,
      additionalRest: 90,
      mediaLink: "https://www.youtube.com/watch?v=J0DnG1_S92I",
      comments:
        "<ul><li>Put your hands close together so the thumbs and index fingers touch, then perform a pushup</li><li>If this is too difficult or feels uncomfortable, put your hands just a bit closer than in a normal pushup. Work on moving the hands closer together over time until you reach diamond pushups</li></ul>",
      duration: false,
    },
  },
  {
    id: 14,
    exercise: {
      id: 14,
      key: "ring-ab-rollouts",
      name: "Ring Ab Rollouts",
      category: "CORE_TRIPLET",
      type: "ANTI_EXTENSION",
      targetSets: 3,
      targetRepsMin: 8,
      targetRepsMax: 12,
      targetRest: 60,
      additionalRest: 60,
      mediaLink: "https://www.youtube.com/watch?v=LBUfnmugKLw",
      comments:
        "<ul><li>Elbows should stay straight</li><li>Remain in a hollow body position (ribs down, butt tucked)</li><li>Keep your hands as close as your overhead mobility will allow.</li><li>Higher ring position will make this easier. Elevating the feet will make it harder.</li></ul>",
      duration: false,
    },
  },
  {
    id: 15,
    exercise: {
      id: 15,
      key: "banded-pallof-press",
      name: "Banded Pallof Press",
      category: "CORE_TRIPLET",
      type: "ANTI_ROTATION",
      targetSets: 3,
      targetRepsMin: 8,
      targetRepsMax: 12,
      targetRest: 60,
      additionalRest: 60,
      mediaLink: "https://www.youtube.com/watch?v=AH_QZLm_0-s",
      comments:
        "<ul><li>These are performed under control with a short pause when your arms are fully extended</li></ul>",
      duration: false,
    },
  },
  {
    id: 16,
    exercise: {
      id: 16,
      key: "reverse-hyperextension",
      name: "Reverse Hyperextension",
      category: "CORE_TRIPLET",
      type: "EXTENSION",
      targetSets: 3,
      targetRepsMin: 8,
      targetRepsMax: 12,
      targetRest: 60,
      additionalRest: 60,
      mediaLink: "https://www.youtube.com/watch?v=ZeRsNzFcQLQ&",
      comments: "<ul><li>Keep your butt tucked</li></ul>",
      duration: false,
    },
  },
];
