name: Run Jest Tests

on:
  push:
    branches: [main]
    paths:
      - "client/**"
  pull_request:
    branches: [main]
    paths:
      - "client/**"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Change to client directory
        run: cd client
      - name: Install dependencies
        run: npm install
        working-directory: ./client
      - name: Run Jest
        run: npm test
        working-directory: ./client
